using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Mizzle.Generators;

[Generator]
public sealed class QueryInterceptorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var interceptors = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is InvocationExpressionSyntax,
                static (ctx, _) => Transform(ctx))
            .Where(static spec => spec is not null)
            .Select(static (spec, _) => spec!)
            .Collect();

        context.RegisterSourceOutput(interceptors, static (spc, specs) => Generate(spc, specs));
    }

    private static InterceptorSpec? Transform(GeneratorSyntaxContext context)
    {
        if (context.Node is not InvocationExpressionSyntax invocation)
        {
            return null;
        }

        if (context.SemanticModel.GetSymbolInfo(invocation).Symbol is not IMethodSymbol { Name: "ToListAsync" } method
            || method.ContainingType.ToDisplayString() != "Mizzle.Fluent.SelectBuilder")
        {
            return null;
        }

        if (!QueryInterceptability.IsInterceptableFluentChain(invocation, context.SemanticModel))
        {
            return null;
        }

#pragma warning disable RSEXPERIMENTAL002
        var location = context.SemanticModel.GetInterceptableLocation(invocation);
        if (location is null)
        {
            return null;
        }

        var attribute = location.GetInterceptsLocationAttributeSyntax();
#pragma warning restore RSEXPERIMENTAL002
        return new InterceptorSpec(attribute);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<InterceptorSpec> specs)
    {
        if (specs.Length == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Mizzle.Generated.Interceptors");
        sb.AppendLine("{");
        sb.AppendLine("    public static class SelectToListInterceptors");
        sb.AppendLine("    {");
        foreach (var spec in specs)
        {
            sb.Append("        ");
            sb.AppendLine(spec.AttributeSyntax);
        }

        sb.AppendLine("        public static global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<T>> ToListAsync<T>(");
        sb.AppendLine("            this global::Mizzle.Fluent.SelectBuilder builder,");
        sb.AppendLine("            global::System.Func<global::System.Data.Common.DbDataReader, T> map,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            using (global::Mizzle.InterceptorScope.Enter())");
        sb.AppendLine("            {");
        sb.AppendLine("                return builder.ToListAsync(map, cancellationToken);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("Mizzle.QueryInterceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed class InterceptorSpec
    {
        public InterceptorSpec(string attributeSyntax) => AttributeSyntax = attributeSyntax;

        public string AttributeSyntax { get; }
    }
}
