using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Mizzle.Generators;

[Generator]
public sealed class QueryInterceptorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var interceptors = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is InvocationExpressionSyntax,
                static (ctx, _) => Transform(ctx))
            .Where(static spec => spec is not null)
            .Select(static (spec, _) => spec!)
            .Collect();

        context.RegisterSourceOutput(interceptors, static (spc, specs) => Generate(spc, specs));
    }

    private static InterceptorSpec? Transform(GeneratorSyntaxContext context)
    {
        if (context.Node is not InvocationExpressionSyntax invocation)
        {
            return null;
        }

        // Delegate overload only (map + ct); the typed terminators belong to ProjectionGenerator.
        if (context.SemanticModel.GetSymbolInfo(invocation).Symbol is not IMethodSymbol { Name: "ToListAsync" } method
            || method.ContainingType.ToDisplayString() != "Mizzle.Fluent.SelectBuilder"
            || method.Parameters.Length != 2)
        {
            return null;
        }

        var spec = BakedChainWalker.TryGetSpec(invocation, context.SemanticModel);
        if (spec is null)
        {
            return null;
        }

        var sql = BakedSqlEmitter.Emit(spec);
        if (sql is null)
        {
            return null;
        }

#pragma warning disable RSEXPERIMENTAL002
        var location = context.SemanticModel.GetInterceptableLocation(invocation);
        if (location is null)
        {
            return null;
        }

        var attribute = location.GetInterceptsLocationAttributeSyntax();
#pragma warning restore RSEXPERIMENTAL002
        return new InterceptorSpec(attribute, sql);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<InterceptorSpec> specs)
    {
        if (specs.Length == 0)
        {
            return;
        }

        var stringBuilder = new StringBuilder();
        stringBuilder.AppendLine("// <auto-generated />");
        stringBuilder.AppendLine("#nullable enable");
        ProjectionGenerator.AppendInterceptsLocationDeclaration(stringBuilder);
        stringBuilder.AppendLine("namespace Mizzle.Generated.Interceptors");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("    public static class MizzleBakedQueries");
        stringBuilder.AppendLine("    {");
        var groups = specs.GroupBy(s => s.Sql).ToList();
        for (var i = 0; i < groups.Count; i++)
        {
            if (i > 0)
            {
                stringBuilder.AppendLine();
            }

            foreach (var spec in groups[i].Select(s => s.AttributeSyntax).Distinct())
            {
                stringBuilder.Append("        ");
                stringBuilder.AppendLine(spec);
            }

            stringBuilder.Append("        public static global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<T>> ToListAsync");
            stringBuilder.Append(i);
            stringBuilder.AppendLine("<T>(");
            stringBuilder.AppendLine("            this global::Mizzle.Fluent.SelectBuilder builder,");
            stringBuilder.AppendLine("            global::System.Func<global::System.Data.Common.DbDataReader, T> map,");
            stringBuilder.AppendLine("            global::System.Threading.CancellationToken cancellationToken = default)");
            stringBuilder.Append("            => builder.ToListPrecompiledAsync(");
            stringBuilder.Append(SymbolDisplay.FormatLiteral(groups[i].Key, quote: true));
            stringBuilder.AppendLine(", map, cancellationToken);");
        }

        stringBuilder.AppendLine("    }");
        stringBuilder.AppendLine("}");

        context.AddSource("Mizzle.QueryInterceptors.g.cs", SourceText.From(stringBuilder.ToString(), Encoding.UTF8));
    }

    private sealed class InterceptorSpec
    {
        public InterceptorSpec(string attributeSyntax, string sql)
        {
            AttributeSyntax = attributeSyntax;
            Sql = sql;
        }

        public string AttributeSyntax { get; }

        public string Sql { get; }
    }
}
