<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>Mizzle</Authors>
    <Version>0.1.0-alpha</Version>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <RepositoryUrl>https://github.com/placeholder/Mizzle</RepositoryUrl>
  </PropertyGroup>
</Project>
