<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Mizzle" />
    <Using Include="Mizzle.Compile" />
    <Using Include="Mizzle.Fluent" />
    <Using Include="Mizzle.Ir" />
    <Using Include="Mizzle.Postgres" />
    <Using Include="Mizzle.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mizzle\Mizzle.csproj" />
    <ProjectReference Include="..\..\src\Mizzle.Postgres\Mizzle.Postgres.csproj" />
    <ProjectReference Include="..\..\src\Mizzle.SqlServer\Mizzle.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\Mizzle.Cli\Mizzle.Cli.csproj" />
  </ItemGroup>

</Project>
