<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);NU1903;NU1603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Mizzle" />
    <Using Include="Mizzle.Fluent" />
    <Using Include="Mizzle.Ir" />
    <Using Include="Mizzle.Postgres" />
    <Using Include="Mizzle.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.7.0" />
    <PackageReference Include="Testcontainers.MsSql" Version="4.7.0" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="Dapper" Version="2.1.66" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mizzle\Mizzle.csproj" />
    <ProjectReference Include="..\..\src\Mizzle.Postgres\Mizzle.Postgres.csproj" />
    <ProjectReference Include="..\..\src\Mizzle.SqlServer\Mizzle.SqlServer.csproj" />
  </ItemGroup>

</Project>
