<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);NU1903;NU1603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="BenchmarkDotNet.Attributes" />
    <Using Include="BenchmarkDotNet.Running" />
    <Using Include="Dapper" />
    <Using Include="Mizzle" />
    <Using Include="Mizzle.Fluent" />
    <Using Include="Mizzle.Postgres" />
    <Using Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.4" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mizzle\Mizzle.csproj" />
    <ProjectReference Include="..\..\src\Mizzle.Postgres\Mizzle.Postgres.csproj" />
    <ProjectReference Include="..\..\src\Mizzle.Generators\Mizzle.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Import Project="..\..\src\Mizzle.Generators\build\Mizzle.Generators.props" />

</Project>
